Controllers/MovieAdminController.cs
using MovieBusinessLogic;
using MovieModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using 影院管理系统.Models;

namespace 影院管理系统.Controllers
{
    public class MovieAdminController : Controller
    {
        // GET: MovieAdmin
        Manager manager = new Manager();
        public ActionResult MIndex()
        {
            return View();
        }

        public ActionResult MInsert()
        {
            return View();
        }

        public ActionResult MDelete()
        {
            return View();
        }

        public ActionResult MUpdate()
        {
            return View();
        }

        public ActionResult MAllinf()
        {
            var posts = manager.GetMovieinfs().Select(post => new AllMViewModel()
            {
                ID=post.ID,
                Name=post.Name,
                Type=post.Type,
                Time=post.Time,
                Ondate=post.Ondate,
                Outdate=post.Outdate,
                Price=post.Price,
                Intro=post.Intro,
                Url=post.Url

            }).ToList();
            var postsList = new AllMListViewModel()
            {
                Count=posts.Count,
                AllMs=posts
            };
            return View(postsList);
        }

        public JsonResult SendNewMovie()
        {
            Movieinf movieinf = new Movieinf()
            {
                ID=Request.QueryString["newid"],
                Name=Request.QueryString["name"],
                Type=Request.QueryString["type"],
                Time=Request.QueryString["time"],
                Ondate=Request.QueryString["ondate"],
                Outdate=Request.QueryString["outdate"],
                Price=float.Parse(Request.QueryString["price"]),
                Intro=Request.QueryString["introduction"],
                Url=Request.QueryString["url"]
            };
            int flag = manager.InsertMovie(movieinf);
            movieinf.flag = flag;
            return Json(movieinf, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SearchtheMovie()
        {
            Movieinf movieinf = new Movieinf()
            {
                ID = Request.QueryString["id"]
            };
            Movieinf movieinf1 = manager.SearchMovie(movieinf);
            return Json(movieinf1, JsonRequestBehavior.AllowGet);

        }

        public JsonResult DeletetheMovie()
        {
            Movieinf movieinf = new Movieinf()
            {
                ID = Request.QueryString["id"]
            };
            int flag = manager.DeleteMovie(movieinf);
            return Json(flag, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdatetheMovie()
        {
            Movieinf movieinf = new Movieinf()
            {
                ID = Request.QueryString["newid"],
                Name = Request.QueryString["name"],
                Type = Request.QueryString["type"],
                Time = Request.QueryString["time"],
                Ondate = Request.QueryString["ondate"],
                Outdate = Request.QueryString["outdate"],
                Price = float.Parse(Request.QueryString["price"]),
                Intro = Request.QueryString["introduction"],
                Url = Request.QueryString["url"]
            };
            string currentid = Request.QueryString["currentid"];
            int flag = manager.UpdateMovie(movieinf, currentid);
            movieinf.flag = flag;
            return Json(movieinf, JsonRequestBehavior.AllowGet);
        }
       
      
    }
}

Views/MovieAdmin/MAllinf.cshtml
@using 影院管理系统.Models;
@model AllMListViewModel
@{
    ViewBag.Title = "MAllinf";
}




<h2>所有影片的信息</h2>
<h3>影院已上架 @Model.Count 部电影</h3>
<ul>
   
    @foreach(var post in Model.AllMs)
    {
    <li>影片ID: @post.ID  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 名字: @post.Name &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 类型: @post.Type &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 时长: @post.Time &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 上映日期: @post.Ondate &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 下线日期: @post.Outdate &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 票价: @post.Price &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 简介: @post.Intro &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 图片url: @post.Url</li>
    }
</ul>

Views/MovieAdmin/MDelete.cshtml

@{
    ViewBag.Title = "MDelete";
}
<style type="text/css">
    #center {
        width: 1000px;
        height: 1000px;
        margin: 0 auto;
        padding-left: 150px;
    }

    h2 {
        text-align: center;
    }

    .left1 {
        width: 300px;
        text-align: left
    }

    .right1 {
        width: 320px;
        height: 50px;
        border: 1px solid #808080
    }

    #getbackbtn {
        visibility: hidden;
    }
</style>

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script type="text/javascript">
    var currentid=0;
    $(document).ready(function ()
    {
        $("#delete").click(function () {
            //alert("test");
            var id = currentid;
            var result = { "id": id };
            $.get('@Url.Action("DeletetheMovie", "MovieAdmin")', result)
                .done(function (data)
                {
                    if (data == 1) {
                        alert("删除影片信息成功!");
                        var result = "<br>删除影片信息成功!对应的ID为:" + id;
                        $("#getback2").html(result);
                    }
                    else { alert("删除影片信息失败!"); }
                })
                .fail(function (data)
                {
                    alert("删除影片信息失败!");
                })


        });

        $("#submitinf").click(function () {
            var id = $("#id").val();
            var result = { "id": id };
            currentid = id;
            $.get('@Url.Action("SearchtheMovie", "MovieAdmin")',result)
                .done(function (data)
                {
                    if (data.flag == 1) {
                        alert("查找影片信息成功!");
                        var result = "<br>成功查找到影片：" + data.Name + "<br>该影片的ID：" + data.ID
                            + "<br>该影片的类型：" + data.Type
                            + "<br>该影片的时长：" + data.Time
                            + "<br>该影片的上线日期：" + data.Ondate
                            + "<br>该影片的下线日期：" + data.Outdate
                            + "<br>该影片的票价：" + data.Price
                            + "<br>该影片的简介：" + data.Intro
                            + "<br>该影片的url：" + data.Url+"<br>";
                            //+ '<table><tr><td><input type="button" class="btn-danger" value="确定删除" id="delect" /></td><td></td></tr></table>';
                        $("#getback").html(result);
                        // $("#getbackbtn").html(btn);
                        $("#getbackbtn").css("visibility","visible");
                    }
                    else
                    {
                        alert("未找到该影片!");
                        var result = "该影片不存在!";
                        $("#getback").html(result);
                    }

                })
                .fail(function (data)
                {
                    alert("查找影片信息失败!");
                })
        });


    }
        )
</script>

    <div id="center">
        <h2>删除影片信息</h2>
        <form>
            <table>
                <tr>
                    <td class="left1">请输入要删除的影片ID：</td>
                    <td><input type="text" class="right1" id="id" /></td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td><input type="reset" class="btn-warning" value="重置信息" /></td>
                    <td><input type="button" class="btn-success" value="提交信息" id="submitinf" /></td>
                </tr>
            </table>
        </form>
        <div id="getback" class="text-warning"></div>
        <div id="getbackbtn"><table><tr><td><input type="button" class="btn-danger" value="确定删除" id="delete" /></td><td></td></tr></table></div>
        <div id="getback2" class="text-danger"></div>
    </div>


Views/MovieAdmin/MIndex.cshtml

@{
    ViewBag.Title = "MIndex";
}
<style type="text/css">
    #useradmin_jumbotron {
        background-color: transparent;
    }

    #rowchangecwb {
        margin-left: 30px;
        margin-right: 30px;
    }
</style>

<div class="jumbotron" id="useradmin_jumbotron">
    <h1>影片管理主页</h1>
    <p class="lead">欢迎来到影片管理主页，在这里你可以添加删除查找或者修改影片的信息!</p>
    <p><a href="MAllinf" class="btn btn-primary btn-lg">查看所有影片 &raquo;</a></p>
</div>

<div class="row" id="rowchangecwb">
    <div class="col-md-4">
        <h2>添加影片信息</h2>
        <p>
            当影院有新的新片要上映时，在这里来添加新影片的信息
        </p>
        <p><a class="btn btn-default" href="MInsert">添加影片 &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>删除影片信息</h2>
        <p>当某些影片因某些原因被下架时，在这里来删除需要下架的影片，与该影片有关的场次影票等其他信息，也会一并删除</p>
        <p><a class="btn btn-default" href="MDelete">删除影片 &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>查看/修改影片信息</h2>
        <p>管理员在这里可以查看影片的信息，查看之后也可以修改影片的信息</p>
        <p><a class="btn btn-default" href="MUpdate">查看修改影片 &raquo;</a></p>
    </div>
</div>



Views/MovieAdmin/MInsert.cshtml

@{
    ViewBag.Title = "MInsert";
}

<style type="text/css">
    #center {
        width: 1000px;
        height: 1000px;
        margin: 0 auto;
        padding-left: 150px;
    }

    h2 {
        text-align: center;
    }

    .left1 {
        width: 300px;
        text-align: left
    }

    .right1 {
        width: 320px;
        height: 50px;
        border: 1px solid #808080
    }
</style>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#submitinf").click(function ()
        {
            //alert("123");
            var newid = $("#newID").val();
            var name = $("#name").val();
            var type = $("#type").val();
            var time = $("#time").val();
            var ondate = $("#ondate").val();
            var outdate = $("#outdate").val();
            var price = $("#price").val();
            var introduction = $("#introduction").val();
            var url = $("#url").val();
            var flag = 1;
            var wrongmessage = "";
            //alert(time);
            //alert(ondate);
            //alert(account.length);
            if (newid.length > 10 || newid.length<1) {
                wrongmessage = "添加失败, 影片ID长度不能多于10位或小于1位\n";
                flag = 0;
            }
            if (introduction.length > 290 || introduction.length<1) {
                wrongmessage += "添加失败，影片的简介长度不能多于290位或小于1位\n";
                flag = 0;
            }
            if (ondate.length == 0 || outdate.length == 0) {
                wrongmessage += "添加失败，影片的上线日期和下线日期不能为空\n";
                flag = 0;
            }
            if (time.length == 0) {
                wrongmessage += "添加失败，影片的时长不能为空\n";
                flag = 0;
            }
            if (price.length == 0) {
                wrongmessage += "添加失败，影片的票价不能为空\n";
                flag = 0;
            }
            if (ondate > outdate) {
                wrongmessage += "添加失败，影片的上线日期不能晚于下线日期\n";
                flag = 0;
            }
            if (flag == 0) {
                alert(wrongmessage);
            }

            else {
                var results = {
                    "newid": newid,
                    "name": name,
                    "type": type,
                    "time": time,
                    "ondate": ondate,
                    "outdate": outdate,
                    "price": price,
                    "introduction": introduction,
                    "url": url
                };
                $.get('@Url.Action("SendNewMovie","MovieAdmin")', results)
                    .done(function (data) {
                        if (data.flag == 1) {
                            alert("添加影片信息成功!");
                            var result = "<br>成功添加新影片：" + data.Name + "<br>该影片的ID：" + data.ID
                                + "<br>该影片的上线日期：" + data.Ondate
                                + "<br>该影片的下线日期：" + data.Outdate
                                + "<br>该影片的时长：" + data.Time
                                + "<br>该影片的票价：" + data.Price
                                + "<br>该影片的类型：" + data.Type
                                + "<br>该影片的简介：" + data.Intro
                                + "<br>该影片的url：" + data.Url;
                        }
                        else {
                            alert("添加影片信息失败!影片的ID或者名字不能重复!")
                            var result = "添加影片信息失败!影片的ID或者名字不能重复!"
                        }
                        $("#getback").html(result);
                        //console.log(data);
                    })
                    .fail(function (data) {
                        alert("添加影片信息失败!");
                        var resultfail = "<br>影片信息添加失败!"
                        $("#getback").html(resultfail);
                    })

            }
        });
    });
</script>


<div id="center">
    <h2>添加影片信息</h2>
    <form>
        <table>
            <tr>
                <td class="left1">新影片ID：</td>
                <td><input type="text" class="right1" id="newID" /></td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td class="left1">新影片名字：</td>
                <td><input type="text" class="right1" id="name" /></td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td class="left1">新影片类型：</td>
                <td><input type="text" class="right1" id="type" /></td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td class="left1">新影片时长：</td>
                <td><input type="time" class="right1" id="time" /></td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td class="left1">新影片上映日期：</td>
                <td><input type="date" class="right1" id="ondate" /> </td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td class="left1">新影片下线日期：</td>
                <td><input type="date" class="right1" id="outdate" /> </td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td class="left1">票价：</td>
                <td><input type="number" min="1" max="999" step="0.01" class="right1" id="price" /> </td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td class="left1">简介：</td>
                <td><input type="text" class="right1" id="introduction" /> </td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td class="left1">图片url：</td>
                <td><input type="text" class="right1" id="url" /> </td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td><input type="reset" class="btn-warning" value="重置信息" /></td>
                <td><input type="button" class="btn-success" value="提交信息" id="submitinf" /></td>
            </tr>
        </table>
    </form>
    <div id="getback" class="text-success"></div>
</div>


Views/MovieAdmin/MUpdate.cshtml

@{
    ViewBag.Title = "MUpdate";
}

<style type="text/css">
    #center {
        width: 1000px;
        height: 1500px;
        margin: 0 auto;
        padding-left: 150px;
    }

    h2 {
        text-align: center;
    }

    .left1 {
        width: 300px;
        text-align: left
    }

    .right1 {
        width: 320px;
        height: 50px;
        border: 1px solid #808080
    }

    #getbackbtn {
        visibility: hidden;
    }

    #getback2 {
        visibility: hidden;
    }
</style>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script type="text/javascript">
    var currentid=0;
    $(document).ready(function ()
    {
        $("#update").click(function () {
            //alert("test")
            $("#getback2").css("visibility", "visible");
        });

        $("#submitinf2").click(function ()
        {
            //alert("123");
            var newid = $("#ID").val();
            var name = $("#name").val();
            var type = $("#type").val();
            var time = $("#time").val();
            var ondate = $("#ondate").val();
            var outdate = $("#outdate").val();
            var price = $("#price").val();
            var introduction = $("#introduction").val();
            var url = $("#url").val();
            var flag = 1;
            var wrongmessage = "";
            //alert(time);
            //alert(ondate);
            //alert(account.length);
            if (newid.length > 10 || newid.length < 1) {
                wrongmessage = "修改失败, 影片ID长度不能多于10位或小于1位\n";
                flag = 0;
            }
            if (introduction.length > 290 || introduction.length < 1) {
                wrongmessage += "修改失败，影片的简介长度不能多于290位或小于1位\n";
                flag = 0;
            }
            if (ondate.length == 0 || outdate.length == 0) {
                wrongmessage += "修改失败，影片的上线日期和下线日期不能为空\n";
                flag = 0;
            }
            if (time.length == 0) {
                wrongmessage += "修改失败，影片的时长不能为空\n";
                flag = 0;
            }
            if (price.length == 0) {
                wrongmessage += "修改失败，影片的票价不能为空\n";
                flag = 0;
            }
            if (ondate > outdate) {
                wrongmessage += "修改失败，影片的上线日期不能晚于下线日期\n";
                flag = 0;
            }
            if (flag == 0) {
                alert(wrongmessage);
            }

            else {
                var results = {
                    "newid": newid,
                    "name": name,
                    "type": type,
                    "time": time,
                    "ondate": ondate,
                    "outdate": outdate,
                    "price": price,
                    "introduction": introduction,
                    "url": url,
                    "currentid": currentid

                };
                $.get('@Url.Action("UpdatetheMovie","MovieAdmin")', results)
                    .done(function (data) {
                        if (data.flag == 1) {
                            alert("修改影片信息成功!");
                            var result = "<br>影片信息修改成功，该影片的名字：" + data.Name + "<br>该影片的ID：" + data.ID
                                + "<br>该影片的类型：" + data.Type
                                + "<br>该影片的时长：" + data.Time
                                + "<br>该影片的上线日期：" + data.Ondate
                                + "<br>该影片的下线日期：" + data.Outdate
                                + "<br>该影片的票价：" + data.Price
                                + "<br>该影片的简介：" + data.Intro
                                + "<br>该影片的url：" + data.Url + "<br>";
                        }
                        else if (data.flag == 2) {
                            alert("修改影片信息失败!影片的名字或ID不能重复!")
                            var result = "<br>修改影片信息失败!影片的名字或ID不能重复!"
                        }
                        else {
                            alert("修改影片信息失败!影片的名字或ID不能重复!")
                            var result = "<br>修改影片信息失败!影片的名字或ID不能重复!"}
                        $("#getback3").html(result);
                        //console.log(data);
                    })
                    .fail(function (data) {
                        alert("修改影片信息失败!");
                        var resultfail = "<br>影片信息修改失败!"
                        $("#getback3").html(resultfail);
                    })

            }

        });

        $("#submitinf").click(function () {
            var id = $("#id").val();
            var result = { "id": id };
            currentid = id;
            $.get('@Url.Action("SearchtheMovie", "MovieAdmin")',result)
                .done(function (data)
                {
                    if (data.flag == 1) {
                        alert("查找影片信息成功!");
                        var result = "<br>成功查找到影片：" + data.Name + "<br>该影片的ID：" + data.ID
                            + "<br>该影片的类型：" + data.Type
                            + "<br>该影片的时长：" + data.Time
                            + "<br>该影片的上线日期：" + data.Ondate
                            + "<br>该影片的下线日期：" + data.Outdate
                            + "<br>该影片的时长：" + data.Time
                            + "<br>该影片的票价：" + data.Price
                            + "<br>该影片的简介：" + data.Intro
                            + "<br>该影片的url：" + data.Url+"<br>";
                            //+ '<table><tr><td><input type="button" class="btn-danger" value="确定删除" id="delect" /></td><td></td></tr></table>';
                        $("#getback").html(result);
                        // $("#getbackbtn").html(btn);
                        $("#getbackbtn").css("visibility", "visible");
                        $("#ID").val(data.ID);
                        $("#name").val(data.Name);
                        $("#type").val(data.Type);
                        $("#time").val(data.Time);
                        $("#ondate").val(data.Ondate);
                        $("#outdate").val(data.Outdate);
                        $("#price").val(data.Price);
                        $("#introduction").val(data.Intro);
                        $("#url").val(data.Url);
                    }
                    else
                    {
                        alert("未找到该影片!");
                        var result = "<br>该影片不存在!";
                        $("#getback").html(result);
                    }

                })
                .fail(function (data)
                {
                    alert("查找影片信息失败!");
                })
        });


    }
        )
</script>

<div id="center">
    <h2>查找/更改影片信息</h2>
    <form>
        <table>
            <tr>
                <td class="left1">请输入要查找/更新的影片ID：</td>
                <td><input type="text" class="right1" id="id" /></td>
            </tr>
            <tr><td><br /></td></tr>
            <tr>
                <td><input type="reset" class="btn-warning" value="重置信息" /></td>
                <td><input type="button" class="btn-success" value="提交信息" id="submitinf" /></td>
            </tr>
        </table>
    </form>
    <div id="getback" class="text-primary"></div>
    <div id="getbackbtn"><table><tr><td><input type="button" class="btn-primary" value="确定更改该影片信息" id="update" /></td><td></td></tr></table></div>
    <div id="getback2">
        <form>
            <table>
                <tr>
                    <td class="left1">影片ID：</td>
                    <td><input type="text" class="right1" id="ID" /></td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td class="left1">影片名字：</td>
                    <td><input type="text" class="right1" id="name" /></td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td class="left1">影片类型：</td>
                    <td><input type="text" class="right1" id="type" /></td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td class="left1">影片时长：</td>
                    <td><input type="time" class="right1" id="time" /></td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td class="left1">影片上映日期：</td>
                    <td><input type="date" class="right1" id="ondate" /> </td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td class="left1">影片下线日期：</td>
                    <td><input type="date" class="right1" id="outdate" /> </td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td class="left1">票价：</td>
                    <td><input type="number" min="1" max="999" step="0.01" class="right1" id="price" /> </td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td class="left1">简介：</td>
                    <td><input type="text" class="right1" id="introduction" /> </td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td class="left1">图片url：</td>
                    <td><input type="text" class="right1" id="url" /> </td>
                </tr>
                <tr><td><br /></td></tr>
                <tr>
                    <td><input type="reset" class="btn-warning" value="重置信息" /></td>
                    <td><input type="button" class="btn-success" value="提交信息" id="submitinf2" /></td>
                </tr>
            </table>
        </form>
    </div>
    <div id="getback3" class="text-success"></div>
</div>