Controllers/ScreeningController.cs
using Screening.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Screening.Controllers
{
    public class ScreeningController : Controller
    {
        // GET: Screening
        public ActionResult Index()
        {
            MovieBusinessLogic.ScreeningManager sc_ma = new MovieBusinessLogic.ScreeningManager();
            var screening_info = sc_ma.GetAllScreenings().Select(s_l => new ScreeningDataModel()
            {
                screening_id = s_l.screening_id,
                film_id=s_l.film_id,
                start_time=s_l.start_time,
                hall_id=s_l.hall_id,
            }).ToList() ;
            var screening_list = new ScreeningList()
            {
                ScreeningDataList=screening_info,
            };

            return View(screening_list);
        }

        [HttpPost]
        public ActionResult Index(string screening_id)
        {
            MovieBusinessLogic.ScreeningManager sc_ma = new MovieBusinessLogic.ScreeningManager();
            sc_ma.DeleteScreeningInfoById(screening_id);
            var screening_info = sc_ma.GetAllScreenings().Select(s_l => new ScreeningDataModel()
            {
                screening_id = s_l.screening_id,
                film_id = s_l.film_id,
                start_time = s_l.start_time,
                hall_id = s_l.hall_id,
            }).ToList();
            var screening_list = new ScreeningList()
            {
                ScreeningDataList = screening_info,
            };




            return View(screening_list);
        }
    }
}

Views/Screening/Index.cshtml
@using Screening.Models
@model ScreeningList
@{
    ViewBag.Title = "Index";
}


<div class="am-u-sm-12">
    <table width="100%" class="am-table am-table-compact am-table-striped tpl-table-black " id="example-r">
        <thead>
            <tr>
                <th>场次ID</th>
                <th>影片ID</th>
                <th>放映时间</th>
                <th>放映厅ID</th>
                <th>座位详情</th>
                <th>操作</th>

            </tr>
        </thead>
        <tbody id="datas">
            @if (Model.ScreeningDataList.Count > 0)
            {
                foreach (var i in Model.ScreeningDataList)
                {
            <tr>
                <td>@i.screening_id</td>
                <td>@i.film_id</td>
                <td>@i.start_time</td>
                <td><a href="@Url.Content("~/Hall/Index/"+i.screening_id)"> @i.hall_id</a></td>
                <td><a href="@Url.Content("~/SeatsList/Index/"+i.screening_id)"> 查看座位详情</a></td>
                <td>
                    @using (Html.BeginForm("Index", "Screening", FormMethod.Post))
                    {
                        <input type="hidden" value=@i.screening_id name="screening_id" />
                        <button type="submit" class="cart-close-btn">删除</button>
                    }
                </td>
                <td>

                    <a href="@Url.Content("~/Modify/Index/"+i.screening_id)">
                        <input type="button" value="修改" name="screening_id" />
                    </a>
                </td>
            </tr>
                }
            }
            <!-- more data -->
        </tbody>
    </table>
</div>