MovieWeb/影院管理系统/Controllers/FilmController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using MovieWeb.Models;
using MovieBusinessLogic;

namespace MovieWeb.Controllers
{
    public class FilmController : Controller
    {

        User user = new User();

        public ActionResult Index(String id)
        {
            id = id == null ? "0" : id;
            ViewBag.mark = 0;
            if (id != null)
            {
                ViewBag.Data = user.getFilmById(id);
                // 如果登录了，去获取该账户是否评分了
                string mark = user.getMark(id);
                //ViewBag.mark = 8;
                ViewBag.mark = (mark == "") ? 0 : float.Parse(mark);
            }

            Session["movieID"] = id;//用于寻找对应影片的用户评论

            string type = ViewBag.Data["类型"];
            string InitialId = ViewBag.Data["影片ID"];
            string[] InitialType = type.Split(' ');
            var recommendMovieList = user.GetRecommendMovies(InitialType, InitialId).Select(movie => new RecommendMovie
            {
                ID = movie.ID,
                Name = movie.Name,
                Type = movie.Type,
                Url = movie.Url
            }).ToList();
            if(Session["uid"]==null)
            {
                var resView = new RecommendMovie()
                {
                    recommendMovies = recommendMovieList,
                    TEXT = "加入收藏",
                    CLASS = "wait_add",
                };
                return View(resView);
            }
            else
            {
                if (!user.isInWishList(Session["uid"].ToString(), Session["movieID"].ToString()))
                {
                    var resView = new RecommendMovie()
                    {
                        recommendMovies = recommendMovieList,
                        TEXT = "加入收藏",
                        CLASS = "wait_add",
                    };
                    return View(resView);
                }
                else
                {
                    var resView = new RecommendMovie()
                    {
                        recommendMovies = recommendMovieList,
                        TEXT = "取消收藏",
                        CLASS = "wait_delete",
                    };
                    return View(resView);
                }
            }   
        }

        //详情页AddWish
        [HttpPost]
        public ActionResult AddWish(string addMovieID)
        {
            Session.Remove("ReturnToWishList");
            if (Session["uid"] == null) return Redirect("/Account");
            string uid = Session["uid"].ToString();
            MovieBusinessLogic.User user = new MovieBusinessLogic.User();
            DateTime nowtime = DateTime.Now;
            if (user.isInWishList(uid, addMovieID) == false)
            {
                var resView = new RecommendMovie()
                {
                    TEXT = "取消收藏",
                    CLASS = "wait_delete",
                };
                user.addWishModels(uid, addMovieID, nowtime);
                return PartialView("FilmPart1", resView);
            }
            else
            {
                var resView = new RecommendMovie()
                {
                    TEXT = "加入收藏",
                    CLASS = "wait_add",
                };
                user.deleteWishModels(uid, addMovieID);
                return PartialView("FilmPart1", resView);
            }
        }

        public ActionResult Search(String key)
        {
            if (Session["uid"] == null) return Redirect("/Account/login");
            if (key == null) key = "1";
            var searchMovies = user.QueryFilm(key).Select(movie => new SearchMovie
            {
                ID = movie.ID,
                Name = movie.Name,
                Type = movie.Type,
                Score = movie.Score,
                Url = movie.Url
            }).ToList();
            var rankMovies = user.GetRankMovies().Select(movie => new RankMovie
            {
                ID = movie.ID,
                Name = movie.Name,
                Tickets = movie.Tickets,
                Url = movie.Url
            }).ToList();
            var searchPageMovies = new SearchPageMovies
            {
                searchMovies = searchMovies,
                rankMovies = rankMovies
            };
            return View(searchPageMovies);
        }
        public void Rate(String id, String s)
        {
            // 验证是否登录 应替换为相应方法
            if (Session["uid"] == null) return;
            string uid = Session["uid"].ToString();
            user.Rate(id, s, uid);
            return;
        }

    }
}

MovieWeb/影院管理系统/Controllers/MovieCommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieBusinessLogic;
using MovieWeb.Models;

namespace MovieWeb.Controllers
{
    public class MovieCommentController : Controller
    {
        // GET: MovieComment
        User user = new User();

        [HttpGet]
        public ActionResult Index()
        {
            string mid = System.Web.HttpContext.Current.Session["movieID"].ToString();
            var comments = user.GetAllComments(mid).Select(comment => new Comment()
            {
                movieID = comment.movieID,
                userID = comment.userID,
                commentTime = comment.commentTime,
                commentContent = comment.commentContent
            }).ToList();
            return View(comments);          
        }

        [HttpPost]
        public ActionResult Index(FormCollection txt)
        {
            
            string content = txt["PostContent"];
            DateTime time = DateTime.Now;
            string mid = System.Web.HttpContext.Current.Session["movieID"].ToString();
            if (Session["uid"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            { 
                string uid = System.Web.HttpContext.Current.Session["uid"].ToString();
                if (user.PostComment(mid, uid, time, content) > 0)
                {
                    
                    ViewBag.commentCode = 1;
                }
                else
                {
                    ViewBag.commentCode = 0;
                }
            }
            return RedirectToAction("Index");
        }
    }
}

MovieWeb/影院管理系统/Views/MovieComment/Index.cshtml
@{
    
}

<script type="text/javascript">
    function cal() {
        var len = document.getElementById('PostContent').value.length;
        var temp = 200 - len;
        if (temp >= 0) {
            document.getElementById('text_count').innerHTML = "剩余可输入" + temp + "字";
        }
        else {
            document.getElementById('PostContent').value = document.getElementById('PostContent').value.substring(0, 200);
        }
    }
</script>
<div class="status-upload">
    <div class="comment-box-control">
        <button class="btn btn-danger"><a href="@Url.Action("Index","Film")?id=@Session["movieID"]">返回</a></button>
    </div>
</div>
    <div class="status-upload">
        <form method="post" action="/MovieComment/Index">
            <textarea runat="server" placeholder="想说点什么..." oninput="cal();" type="text"id="PostContent" name="PostContent"></textarea>
            <div class="comment-box-control">
                <span id="text_count"> 剩余可输入200字</span>            
                <button type="submit" class="btn pull-right">发表</button>
            </div>
        </form>
        @if (ViewBag.commentCode == 1)
        {
            <p class="text-danger" style="font-size:16px; color:white;text-align:center;">发表成功</p>
        }
        @if (ViewBag.commentCode == 0)
        {
            <p class="text-danger" style="font-size:16px; color:white;text-align:center;">发表失败</p>
        }

    </div>

@foreach (MovieWeb.Models.Comment i in Model)
{
        <div class="col-sm-1">
            <div class="thumbnail">
                <img class="img-responsive user-photo" src="~/img/user-header.JPG" alt="Comment User Avatar">
            </div>
        </div>
        <div class="col-sm-11">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>@i.userID</strong> <span class="pull-right">@i.commentTime</span>
                </div>
                <div class="panel-body">@i.commentContent</div>
            </div>
        </div>
}


